mediaedge/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publisher.urls', namespace="publisher")),
]

publisher/urls.py
from django.urls import path 
from publisher import views 
from django.conf import settings 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 

app_name = "publisher"
urlpatterns = [
    path('news-list/<int:current_count>/', views.news_list, name="news_list"),
    path('publish/<int:pk>/', views.publish_article, name="publish-article"),
    path('notify-admin/', views.notify_admin_of_button_click, name="celery_notify_admin"),
    path('', views.home, name="home")
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

publisher/models.py
from django.db import models
from django.utils.text import slugify 
from django.utils import timezone 
from django.contrib.auth.models import User 

# Create your models here.
class News(models.Model):
    """
    Represents a single news article on the MediaEdge's publisher app.
    """
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=170, blank=True)
    body = models.TextField()
    author = models.ForeignKey(User, related_name="articles_written", on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(editable=False, null=True)
    publish = models.BooleanField(default=False)

    class Meta:
        verbose_name = "News Article"
        verbose_name_plural = "News Articles"
        ordering = ['-last_updated','-pub_date',]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if self.pub_date:
            self.last_updated = timezone.now()
        super(News, self).save(*args, **kwargs)

    def __str__(self):
        return "%s by %s " % (self.title, self.author.username)

publisher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse 
from django.views.decorators.cache import cache_page 
from django.conf import settings 
from publisher.models import News 
from publisher.tasks import send_admin_notification

# Create your views here.
def news_list(request, current_count):
    """
        Responds to a jQuery Ajax request to send the latest list 
        of published News articles to the home page in JSON format.
    """
    news_articles = News.objects.filter(publish=True)
    if len(news_articles) == current_count:
        return redirect('publisher:home')
    else:
        return JsonResponse(list(news_articles.values()), safe=False)

@cache_page(60* 0.125)
def home(request):
    """
        The single public-facing page of the app.
    """
    default_article = News.objects.filter(publish=True)[0]
    context_data = {
        'default_article': default_article
    }
    return render(request, "publisher/news_list.html", context_data)

def publish_article(request, pk):
    """
    Called by the custom 'Publish' button in admin's News change page
    to publish a News article.
    """
    article = get_object_or_404(News, pk=pk)
    article.publish = True
    article.save()
    return redirect('/admin/publisher/news/')

def notify_admin_of_button_click(request):
    """
    View that calls a Celery task to initiate sending an email to admin
    to notify them of someone clicking on the 'Help' button.
    """
    subject = "A User Clicked on the 'Help' Button"
    message = """
    Hello Admin, \n 
        A User just clicked on the 'Help' button on the homepage.
        \n 
        Sincerely,\n
        Celery Mailer
    """
    from_email = settings.CELERY_TASKS_EMAIL 
    recipient_list = ['edgeops@mediaedge.com','cto@mediaedge.com','techlead@mediaedge.com']
    send_admin_notification.delay(
        subject, message,
        from_email, recipient_list
    )
    return redirect('publisher:home')

publisher/templates/publisher/news_list.html
<!doctype html>
<html lang="en">
  <head>
      {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Media Edge: News You Can Share</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">MediaEdge</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'publisher:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Authors</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-warning" href="{% url 'publisher:celery_notify_admin' %}">Help</a>
            </li>
         </ul>
        </div>
      </nav>
    </header>
    <!-- Begin page content -->
    <main role="main" class="container">
        <div class="col-xs-12 col-sm-10 col-md-8" style="padding-top:3%;">
            <h4 class="mt-5 text-center">News of the Day</h3>
        </div>
    
    <div class="container" id="article_list">
        <div class="col-xs-12 col-sm-10 col-md-10 col-sm-offset-2 news_article">
                <h4 class="text-center article_title">
                    {{ default_article.title|title }}
                </h4>
                <small class='text-center'>
                   by {{ default_article.author|title }}
                </small>
            <div class='article_body'>{{ default_article.body|safe }}</div>
        </div>

        
    </div>
    <span id="article-count">5</span>
    </main>

    <footer class="footer" style="bottom: 1px;">
      <div class="container">
        <span class="text-muted">(c)2019. MediaEdge. All rights reserved. </span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'publisher/js/news.js' %}"></script>
</body>
</html>